### ISSUE TITLE
Support rspec-rails 3.2.

### ISSUE THREAD

**Issue by joshuapinter** [thekompanee/fuubar#77]
Hi There, 

Great little gem by the way. Love the succinct output.

I'm trying to update `rspec-rails` to 3.2 to avoid an issue with Ruby 2.2.0 and it looks like there are some dependencies in your library on an older version of `rspec-expectations`. This is the error I get when trying to `bundle update rspec-rails`:

```bash
Bundler could not find compatible versions for gem "rspec-expectations":
  In Gemfile:
    fuubar (>= 0) ruby depends on
      rspec (~> 3.0) ruby depends on
        rspec-expectations (~> 3.1.0) ruby

    rspec-rails (~> 3.2.0) ruby depends on
      rspec-expectations (3.2.0)
```

Let me know your thoughts. 

Thanks!

Josh

**Comment by jfelchner** [comment]
@joshuapinter this usually happens due to the developer not using the correct form of `bundle update`.

You need to make sure you tell bundler that it's ok to update gems which don't depend on other gems.  In your example my guess would be to do something like:

`bundle update rspec-rails rspec fuubar`

**Comment by jfelchner** [comment]
Please reopen if this doesn't solve your issue.

**Comment by joshuapinter** [comment]
:+1: Worked great, thanks!
