### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by jmuheim** [thekompanee/fuubar#84]
During running, the indicator doesn't change, and the time is only question marks:

![image](https://cloud.githubusercontent.com/assets/1814983/12063338/8436a362-afad-11e5-81d7-f736067719a7.png)

And when finished:

![image](https://cloud.githubusercontent.com/assets/1814983/12063344/a011f3e8-afad-11e5-992f-567972a45ce3.png)

Using fuubar 2.0.0 and rails 4.2.1.

**Comment by dreyks** [comment]
Make sure you are not traveling in time in before(:all) blocks

**Comment by jmuheim** [comment]
Aaaah, this might be the problem. Thank you!

**Comment by jfelchner** [comment]
Actually time traveling should not affect the progress bar at all. If that fixes it I need to know.

**Comment by dreyks** [comment]
I'm pretty sure that I had this problem when I moved from TimeCop to rails' native travel_to. 
I'll try to come up with an isolated example tomorrow

**Comment by jfelchner** [comment]
@dreyks Ah, that's almost certainly the problem.

`<rant>`
Instead of using the same two gems (Delorean and Timecop) that 90% of everyone else uses, DHH decided Rails needed to roll its own with almost the exact same code (very similar to what they did when they basically copied `better_errors` and put it in Rails instead of just leaving it as its own gem), which means it's another thing that we all now need to support.
`</rant>`

If you can get me an isolated example and post an issue over on https://github.com/jfelchner/ruby-progressbar, I'd appreciate it.

**Comment by dreyks** [comment]
jfelchner/ruby-progressbar#106

**Comment by jmuheim** [comment]
Here's how I fixed it:

```ruby
RSpec.configure do |config|
  config.include ActiveSupport::Testing::TimeHelpers

  config.before(:each) do
    travel_to DateTime.parse('2015-06-15 14:33:52 +0200')
  end

  config.after(:each) do
    travel_back
  end
end
```

**Comment by jfelchner** [comment]
I'll fix this properly in ruby-progressbar with @dreyks PR.
