### ISSUE TITLE
Make fuubar print the file?

### ISSUE THREAD

**Issue by manavortex** [thekompanee/fuubar#96]
Hello,

while I find it rather enjoyable to know which of my test cases took how long - how can I see in which order they are run? 
Can I somehow include that in the stacktrace?

Thanks! Awesome gem!

**Comment by jfelchner** [comment]
@manavortex I'm not entirely sure what you're asking.  Can you give me more details?

**Comment by manavortex** [comment]
I get a counter and a timer, but I have no way of seeing which test is currently running. 
I'll provide a clearer explanation on monday when I run a test, if I can get Selenium back to work. :)

**Comment by shlima** [comment]
+1

**Comment by jfelchner** [comment]
@manavortex I'm going to close this due to lack of activity.  I'd suggest you look into the "documentation" formatter which might be more along the lines of what you're looking for.  I believe you can also apply two formatters to an RSpec run at once.  If you apply both "documentation" and "fuubar", that might be close to what you'd like.

As far as showing the name of the test that's running in the progressbar, that's not something I'm interested in doing.  For most test runs, where the tests run quickly, it would be visually hard to look at.

**Comment by manavortex** [comment]
Thank you @jfelchner :)
